# general config
title: IlluminatorCologne
description: Github Pages
baseurl: ""

# theme config
theme: jekyll-theme-minimal
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme


# Do not show download links
show_downloads: false

#google_analytics: [Your Google Analytics tracking ID]